### ISSUE TITLE
Check for changes between branch prior to creating GH Merge PR

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn-tools#1090]
Problem:
"I'm noticing that the GitHubCreateMergePRs tool from roslyn-tools is continually restoring and deleting branches on a 3-hour interval. It creates noise in our repo when you want to look at recently updated PRs (without filtering out the bot as an author). "

Proposal:
I believe we could perform a "Compare" to see if there are changes between branches prior to this line https://github.com/dotnet/roslyn-tools/blob/main/src/GitHubCreateMergePRs/Program.cs#L77

**Comment by RikkiGibson** [comment]
It looks like we rely on a special status code returned from the call to create a PR to realize there are no commits. I agree that the right thing to do is probably to list "commits which are in the head SHA but not in the base" before creating the merge branch, and avoid creating the merge branch if the list is empty. If the GitHub APIs have a cheaper way to make this check, that could be fine too.

https://github.com/dotnet/roslyn-tools/blob/d784c4c1c1d7613545af96c68611cd4063184176/src/GithubMergeTool/GithubMergeTool.cs#L224-L236
