### ISSUE TITLE
RepoToolset fails on macOS

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/roslyn-tools#172]
I'm trying to use repotoolset to compile the dotnet/arcade repo on macOS, and I get the following error

> /Users/namc/.nuget/packages/roslyntools.repotoolset/1.0.0-beta-62614-02/tools/RepoLayout.props(37,5): error MSB4185: The function "GetFolderPath" on type "System.Environment" is not available for execution as an MSBuild property function.

It looks like the problem is here:

https://github.com/dotnet/roslyn-tools/blob/578061198321be548cb63cef5002b8670a05d1e1/sdks/RepoToolset/tools/RepoLayout.props#L37

Using: dotnet 2.1.300-preview2-008251, macOS 10.13

cc @tmat

**Comment by tmat** [comment]
@tannergooding Have you seen anything similar in CLI repos?

**Comment by Anipik** [comment]
I am also facing the similar issue when i am trying to add a new *csproj to a *sln file in arcade repo on mac Os
