### ISSUE TITLE
csc.exe bundled in RepoToolset exit code 8 on macOS

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/roslyn-tools#173]
I'm trying to compile this on macOS: https://github.com/dotnet/arcade/pull/35

After working around https://github.com/dotnet/roslyn-tools/issues/172, I get this error:

```
/Users/namc/dev/dotnet/arcade/packages/microsoft.net.compilers/2.7.0-beta2-62330-02/tools/Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.exe" exited with code 8
```

dotnet --info:
```
.NET Command Line Tools (2.1.100-preview-007366)

Product Information:
 Version:            2.1.100-preview-007366
 Commit SHA-1 hash:  8265c551de

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /Users/namc/.dotnet/sdk/2.1.100-preview-007366/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview2-26131-06
  Build    : b13a0d5c331f374afd35ded57b9a4b4ab128864c
```
[msbuild.binlog.zip](https://github.com/dotnet/roslyn-tools/files/1768676/msbuild.binlog.zip)

cc @tmat

**Comment by tmat** [comment]
@jaredpar

**Comment by jaredpar** [comment]
Unfortunately the binary logger isn't giving any help here, just has the same message. Wonder if this is another case where msbuild is swallowing the actual compiler output. @natemcmaster can you try invoking the compiler manually and seeing what the output is. Here is the approximate command line based on the log. 

> /Users/namc/dev/dotnet/arcade/packages/microsoft.net.compilers/2.7.0-beta2-62330-02/build/../tools/csc.exe /noconfig /unsafe- /checked+ /nowarn:1701,1702,1705,1591,1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;TRACE;TRACE;DEBUG;NETCOREAPP2_0 /highentropyva+ /reference:/Users/namc/dev/dotnet/arcade/packages/microsoft.build.framework/15.1.548/lib/netstandard1.3/Microsoft.Build.Framework.dll /reference:/Users/namc/dev/dotnet/arcade/packages/microsoft.build.utilities.core/15.1.548/lib/netstandard1.3/Microsoft.Build.Utilities.Core.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/Microsoft.CSharp.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/Microsoft.VisualBasic.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/Microsoft.Win32.Primitives.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/mscorlib.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/netstandard.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.AppContext.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Buffers.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Collections.Concurrent.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Collections.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Collections.Immutable.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Collections.NonGeneric.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Collections.Specialized.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.ComponentModel.Annotations.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.ComponentModel.Composition.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.ComponentModel.DataAnnotations.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.ComponentModel.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.ComponentModel.EventBasedAsync.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.ComponentModel.Primitives.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.ComponentModel.TypeConverter.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Configuration.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Console.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Core.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Data.Common.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Data.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Diagnostics.Contracts.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Diagnostics.Debug.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Diagnostics.DiagnosticSource.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Diagnostics.FileVersionInfo.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Diagnostics.Process.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Diagnostics.StackTrace.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Diagnostics.TextWriterTraceListener.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Diagnostics.Tools.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Diagnostics.TraceSource.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Diagnostics.Tracing.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Drawing.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Drawing.Primitives.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Dynamic.Runtime.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Globalization.Calendars.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Globalization.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Globalization.Extensions.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.IO.Compression.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.IO.Compression.FileSystem.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.IO.Compression.ZipFile.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.IO.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.IO.FileSystem.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.IO.FileSystem.DriveInfo.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.IO.FileSystem.Primitives.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.IO.FileSystem.Watcher.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.IO.IsolatedStorage.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.IO.MemoryMappedFiles.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.IO.Pipes.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.IO.UnmanagedMemoryStream.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Linq.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Linq.Expressions.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Linq.Parallel.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Linq.Queryable.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Net.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Net.Http.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Net.HttpListener.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Net.Mail.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Net.NameResolution.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Net.NetworkInformation.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Net.Ping.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Net.Primitives.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Net.Requests.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Net.Security.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Net.ServicePoint.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Net.Sockets.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Net.WebClient.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Net.WebHeaderCollection.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Net.WebProxy.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Net.WebSockets.Client.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Net.WebSockets.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Numerics.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Numerics.Vectors.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.ObjectModel.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Reflection.DispatchProxy.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Reflection.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Reflection.Emit.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Reflection.Emit.ILGeneration.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Reflection.Emit.Lightweight.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Reflection.Extensions.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Reflection.Metadata.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Reflection.Primitives.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Reflection.TypeExtensions.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Resources.Reader.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Resources.ResourceManager.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Resources.Writer.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Runtime.CompilerServices.VisualC.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Runtime.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Runtime.Extensions.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Runtime.Handles.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Runtime.InteropServices.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Runtime.InteropServices.RuntimeInformation.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Runtime.InteropServices.WindowsRuntime.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Runtime.Loader.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Runtime.Numerics.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Runtime.Serialization.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Runtime.Serialization.Formatters.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Runtime.Serialization.Json.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Runtime.Serialization.Primitives.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Runtime.Serialization.Xml.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Security.Claims.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Security.Cryptography.Algorithms.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Security.Cryptography.Csp.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Security.Cryptography.Encoding.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Security.Cryptography.Primitives.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Security.Cryptography.X509Certificates.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Security.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Security.Principal.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Security.SecureString.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.ServiceModel.Web.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.ServiceProcess.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Text.Encoding.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Text.Encoding.Extensions.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Text.RegularExpressions.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Threading.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Threading.Overlapped.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Threading.Tasks.Dataflow.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Threading.Tasks.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Threading.Tasks.Extensions.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Threading.Tasks.Parallel.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Threading.Thread.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Threading.ThreadPool.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Threading.Timer.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Transactions.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Transactions.Local.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.ValueTuple.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Web.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Web.HttpUtility.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Windows.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Xml.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Xml.Linq.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Xml.ReaderWriter.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Xml.Serialization.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Xml.XDocument.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Xml.XmlDocument.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Xml.XmlSerializer.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Xml.XPath.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Xml.XPath.XDocument.dll /reference:/Users/namc/.dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/WindowsBase.dll /debug+ /debug:embedded /delaysign- /filealign:512 /keyfile:/Users/namc/.nuget/packages/roslyntools.repotoolset/1.0.0-beta-62614-02/tools/35MSSharedLib1024.snk /nologo /optimize- /out:/Users/namc/dev/dotnet/arcade/artifacts/Debug/obj/Microsoft.DotNet.Build.Tasks.IO/netcoreapp2.0/Microsoft.DotNet.Build.Tasks.IO.dll /target:library /warnaserror- /utf8output /deterministic+ /publicsign+ src/Chmod.cs src/DownloadFile.cs src/GetFileHash.cs src/Internal/ArgumentEscaper.cs src/Internal/FileHelpers.cs src/Internal/HashHelper.cs src/UnzipArchive.cs src/VerifyFileHash.cs src/ZipArchive.cs "/Users/namc/dev/dotnet/arcade/artifacts/Debug/obj/Microsoft.DotNet.Build.Tasks.IO/netcoreapp2.0/.NETCoreApp,Version=v2.0.AssemblyAttributes.cs" /Users/namc/dev/dotnet/arcade/artifacts/Debug/obj/Microsoft.DotNet.Build.Tasks.IO/netcoreapp2.0/Microsoft.DotNet.Build.Tasks.IO.AssemblyInfo.cs /warnaserror+:NU1605

**Comment by natemcmaster** [comment]
I'm assuming the problem here is that RepoTools is using Microsoft.Net.Compilers, which requires .NET Framework. Do we need Microsoft.**NETCore**.Compilers?

**Comment by jaredpar** [comment]
@natemcmaster ah yes that's a good point. That is definitely using the desktop toolset.

**Comment by natemcmaster** [comment]
It appears RepoToolset adds the packagereference to Microsoft.Net.Compilers. I found the right magic property to disable

`<UsingToolMicrosoftNetCompilers>false</UsingToolMicrosoftNetCompilers>`

**Comment by natemcmaster** [comment]
It looks like the import to Compiler.props happens before Directory.Build.props is imported. This means we cannot use the Sdk attribute in projects because UsingToolMicrosoftNetCompilers can't be set before implicit top/bottom imports.

**Comment by natemcmaster** [comment]
I found the right place. If you set `UsingToolMicrosoftNetCompilers` from build/Versions.props, it can disable that implicit package reference.

Closing as I found a solution. Not sure there is any action required here for repotoolset...although it was a pain to find this answer.
