### ISSUE TITLE
Change 'build' folder name

### ISSUE THREAD

**Issue by chcosta** [dotnet/roslyn-tools#175]
RepoToolset is using the `$(RepoRoot)build` folder location for build stuff.   There's discussion in https://github.com/dotnet/arcade/issues/33, where it was decided to change the folder structure to something like

```
\eng
   \core
   \tools
```

Arcade cannot make this change until RepoToolset is updated.

**Comment by sharwell** [comment]
To me this is so unfortunate. When I see **build**, I know what I'm going to get when I click it. When I see **eng**, I have no idea.

**Comment by tmat** [comment]
Fixed.
