### ISSUE TITLE
Locate-VS should support pre-Dev15

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn-tools#18]
Doing this will allow us to route all locating of VS through a single call to `LocateVS` and will additionally allow people to differentiate between errors in the LocateVS or ManagedQuery APIs and errors in locating VS itself.

**Comment by tannergooding** [comment]
Going to close this. The https://github.com/microsoft/vswhere tool should be used instead.

**Comment by jaredpar** [comment]
#17334 takes us to vswhere and will be merged in the AM
