### ISSUE TITLE
Insertion tool should warn if it's skipping over newer builds

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn-tools#206]
The insertion tool's logic is:

1. Find the oldest passing build.
2. Insert that.
3. If it turns out no files changed, then simply don't create a PR and call it a "skip".

This can backfire if the oldest passing build is the build that's already inserted, and the reason it picked that build is because the newer builds were all failing. If that's the case, it should treat that as failure, not as a false "success".

**Comment by dsplaisted** [comment]
Relevant code looks to be here:

https://github.com/dotnet/roslyn-tools/blob/09e4b366461ec90cddd4a77660b5dfdfbe01d0d2/src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs#L232
https://github.com/dotnet/roslyn-tools/blob/09e4b366461ec90cddd4a77660b5dfdfbe01d0d2/src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs#L74
