### ISSUE TITLE
Automatic GitHub merges should run every 10 minutes

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn-tools#217]
Right now we are kicking off new inter-branch merges every midnight Pacific Time, but we'd like to ramp this up to every few minutes so we can flow things immediately when they're merged.

**Comment by jasonmalinowski** [comment]
The current status of this is we configured this, and it was working for awhile, but it seems the configuration didn't stick. We don't quite understand why.

**Comment by sharwell** [comment]
Speaking from experience, this approach can add a surprising amount of noise to the repository. Seeing the reduced rate here was a welcome change compared to a former project I worked on.

**Comment by nguerrera** [comment]
Please don't make this run every 10 minutes

**Comment by JoeRobich** [comment]
Since we moved to msftbot, I will close this issue.
