### ISSUE TITLE
Insertion branches for pull requests need to be cleaned up automatically

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn-tools#221]
It's not uncommon we forget to delete merged insertion branches, or forget to merge them entirely. The insertion tool should probably clean up old branches after a few weeks since we accumulate hundreds of them.

**Comment by RikkiGibson** [comment]
VS has been cleaning up these old branches for us. Search email for "NOTICE: stale git branches expired!"

Feel free to reopen if you are still interested in having us clean them up though.
