### ISSUE TITLE
Insertion tool creates pull requests if there are only whitespace changes

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn-tools#222]
The insertion tool creates pull requests whenever it updates any file on disk. If we're trying to insert a build that is already the inserted build, and this implicitly changes whitespace in a file (because we didn't round-trip it), we end up creating pull requests. This gets confusing because it looks like something is being updated but it isn't.

The fix (I think) is before creating the commit, look at all modified files and unpend any changes that are whitespace only changes.

**Comment by RikkiGibson** [comment]
I think this is no longer a problem
