### ISSUE TITLE
Artifact layout and new SDK

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn-tools#37]
The proposed artifact layout has the following structure:

```
artifacts
  $(Configuration)
    obj
       $(MSBuildProjectName)
```

I do not believe that will work with the new SDK and project.assets.json. The NuGet model uses a single project.assets.json for all configurations. In this layout there doesn't appear to be anywhere to put that file. 

Roslyn originally had this model but we had to modify it to support project.assets.json to the following:

```
Binaries
  Obj
    $(MSBuildProjectName)
      $(Configuration) 
```

**Comment by jaredpar** [comment]
CC @tmat

**Comment by tmat** [comment]
I don't see any issues in repos using RepoToolset. They have the former layout: https://github.com/dotnet/roslyn-tools/blob/master/docs/RepoToolset.md

**Comment by jaredpar** [comment]
Where do the project.asset.json files get generated to in the artifacts directory?

**Comment by tmat** [comment]
```
artifacts\Debug\obj\Microsoft.DiaSymReader.PortablePdb\project.assets.json
artifacts\Release\obj\Microsoft.DiaSymReader.PortablePdb\project.assets.json
```

**Comment by jaredpar** [comment]
That looks like you are forcing a restore per configuration then with this layout. That shouldn't be necessary.

**Comment by tmat** [comment]
That's correct. I'll see if we can switch to the other layout.

**Comment by tmat** [comment]
Fixed.
