### ISSUE TITLE
[RIT] Allow an existing PR to be appended to instead of replaced.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn-tools#396]
Currently the `OverwriteExistingPr.ps1` script (and matching Release Definition) always do a force push to the branch specified by the PR.

An additional `AppendExistingPr.ps1` script and the matching Release Definition should be added for the times when it's requested that an existing PR has important work but still needs an insertion.

**Comment by AbhitejJohn** [comment]
This has been addressed as part of #426.
