### ISSUE TITLE
Update the VS repo's Roslyn version number when the dotnet/roslyn version number bumps

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn-tools#493]
For example, when we bumped the Roslyn version from 3.1.0 to 3.2.0, we also needed to manually update AssemblyVersions.tt and versions.xml in the VS repo. See https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/177320?_a=updates for this example.

The insertion tool should do this automatically.

**Comment by JoeRobich** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/36179
