### ISSUE TITLE
UpdateExistingPr uses file version from base branch instead of from PR

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn-tools#587]
Essentially this check happens later than it should, so we end up using and modifying file versions from the base branch, overwriting other changes to those files in the existing PR:

https://github.com/dotnet/roslyn-tools/blob/8608f6754b869da20cc6cae9ecbb033d2025f65e/src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.cs#L257

/cc @shyamnamboodiripad @AbhitejJohn

**Comment by shyamnamboodiripad** [comment]
Here's a link to an example insertion PR where we ran into problems because of this - https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/211781
