### ISSUE TITLE
Improve heuristic for commit log filtering

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn-tools#618]
We currently have heuristic where any PRs merged by the bot are assumed to be "code-flow" PRs, i.e. another PR has already been merged containing the change. So we don't display it in the list of changes in the insertion description. I have noticed some cases where people like to use the auto-merge tag so that they don't have to babysit their PR, though. Maybe there's a better heuristic we can use besides "did the bot merge it"--perhaps a tag for "release-flow". /cc @JoeRobich @333fred

https://github.com/dotnet/roslyn-tools/blob/68acd5a50cf31beed70ed944ce584ffdae89465f/src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs#L494

**Comment by 333fred** [comment]
Yeah, that would be good. I've definitely started to use it now that I know that it works.
