### ISSUE TITLE
Clean up deleted branches in config.xml

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn-tools#652]
In a given run of [GitHub Merge PR Creation](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3360286) we see that there are a few NotFound and similar errors. This probably indicates that some config.xml entries should be deleted.

**Comment by JoeRobich** [comment]
Resolved by https://github.com/dotnet/roslyn-tools/pull/710
