### ISSUE TITLE
Make the RIT merge commit more descriptive

### ISSUE THREAD

**Issue by dmonroym** [dotnet/roslyn-tools#708]
This is a standard message for every insertion this tool is making now. Instead it could include PR # and/or title
https://github.com/dotnet/roslyn-tools/blob/c8fc9dd217ce2fb69e2ac3bca70409300a0c8db1/src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs#L237

**Comment by RikkiGibson** [comment]
maybe include the component+build number that was inserted? Or do we already get that from the PR title?
