### ISSUE TITLE
RIT does not compare SemVer correctly

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn-tools#719]
Roslyn changed from using `beta1` as the prerelease label to using `1`. Our version numbers changed from the form '3.5.0-beta4-20121-02' to the form '3.6.0-1.20121.8'.

I noticed that once the build number for the day got into the double digits that it no longer updated the Roslyn version being inserted. Looking at the RIT log. 

With version '3.6.0-1.20121.8' being inserted the following log was produced.
```
2020-02-21T22:03:58.6176287Z Processing package 'Roslyn-Signed/VSSetup\DevDivPackages\VS.ExternalAPIs.Roslyn.3.6.0-1.20121.12.nupkg'
2020-02-21T22:03:58.6176882Z Package 'VS.ExternalAPIs.Roslyn.3.6.0-1.20121.12' doesn't need to be inserted, version is lower than or equal to the one already inserted.
```

**Comment by RikkiGibson** [comment]
Are we sure of whether it's easier to change the arcade bits that stamp the build number or the RIT bits that interpret the version string?

We could just modify the tool to split off at the last '.' and use an int comparison. But maybe it's a little bit brittle?

**Comment by JoeRobich** [comment]
@RikkiGibson First thing to check is whether SemVer expects .12 to be higher than .8. Everything else would flow from that.

**Comment by JoeRobich** [comment]
Looking at the SemVer 2 spec (https://github.com/semver/semver/blob/master/semver.md):

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. **Numeric identifiers MUST NOT include leading zeroes**. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.--.
