### ISSUE TITLE
How to - pick different VSTS drops to insert in one build

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/roslyn-tools#979]
Hi teams, after dev17 comes out, our build pipeline has a little change and now it uploads two VSTS drops (one for dev16 and the other for dev17) to cloud. However, it looks like rit always fetches the VSTS drop from the first VSTS upload task in build pipeline. And other VSTS upload tasks will be ignored. Is there other way to set up rit.exe so it will fetch VSTS drops info from a specific task name, or from VSTS drop folder?

https://github.com/dotnet/roslyn-tools/blob/330fbb6323fb0bcfa0445f99522ef25c2323322c/src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs#L542

**Comment by LittleLittleCloud** [comment]
Hi @RikkiGibson 
Not quite, we are hoping to have two separate insertions for Dev16 drop and Dev17 drop. Is that what you mean?

**Comment by RikkiGibson** [comment]
OK, got it. It sounds like if we added a parameter to let you replace `"Upload VSTS Drop"` with something else then you'd be able to do what you need to do.
